channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=22.3.1
- pip:
  - mlflow==2.14.1
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightgbm==4.4.0
  - matplotlib==3.9.0
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - psutil==6.0.0
  - pyarrow==15.0.2
  - pyyaml==6.0.1
  - scikit-learn==1.5.0
  - scipy==1.13.1
name: mlflow-env
